version: '3.8'
  services:
    greptimedb:
      image: 'greptime/greptimedb:latest'
      container_name: greptimedb-r2
      entrypoint:
        - /bin/sh
        - '-c'
      command:
        - |
          cat <<EOF > /tmp/greptime-config.toml
          data_home = "/data/home"

          [storage]
          type = "S3"
          bucket = "ohlcv"
          root = "/data"
          endpoint = "https://1c0536c91a38db1b8f5607f69c452b27.r2.cloudflarestorage.com"
          access_key_id = "\${R2_ACCESS_KEY_ID}"
          secret_access_key = "\${R2_SECRET_ACCESS_KEY}"
          region = "auto"
          cache_path = "/data/read_cache"
          cache_capacity = "200GiB"

          [storage.http_client]
          pool_max_idle_per_host = 1024
          connect_timeout = "5s"
          timeout = "60s"

          [wal]
          provider = "raft_engine"
          dir = "/data/home/wal"
          sync_write = false

          [[region_engine]]
          [region_engine.mito]
          num_workers = 8
          max_background_jobs = 8
          enable_write_cache = true
          write_cache_path = "/data/write_cache"
          write_cache_size = "20GiB"
          enable_refill_cache_on_read = true
          sst_meta_cache_size = "512MiB"
          vector_cache_size = "1GiB"
          page_cache_size = "8GiB"
          selector_result_cache_size = "1GiB"

          [region_engine.mito.index]
          aux_path = "/data/home/index"
          metadata_cache_size = "1GiB"
          content_cache_size = "8GiB"
          EOF

          exec greptime standalone start -c /tmp/greptime-config.toml \
            --http-addr 0.0.0.0:4000 \
            --rpc-bind-addr 0.0.0.0:4001 \
            --mysql-addr 0.0.0.0:4002 \
            --postgres-addr 0.0.0.0:4003 \
            --user-provider=static_user_provider:cmd:admin=\${GREPTIME_ADMIN_PASSWORD}
      env_file: .env
      ports:
        - '4000:4000'
        - '4001:4001'
        - '4002:4002'
        - '4003:4003'
      volumes:
        - 'greptime-data:/data'
      ulimits:
        nofile: 65536
      restart: unless-stopped
  volumes:
    greptime-data: null
